export { default as Academy } from "./Academy/Academy";
export { default as Brands } from "./Brands/Brands";
export { default as Ceo } from "./Ceo/Ceo";
export { default as Footer } from "./Footer/Footer";
export { default as Main } from "./Main/Main";
export { default as Services } from "./Services/Services";
export { default as Passion } from "./Passion/Passion";
export { default as Navbar } from "./Navbar/Navbar";
export { default as Career } from "./Career/Career";
